--==================================================
-- SoundLibrary.luau
-- サウンドID定義（shared）
--==================================================

local SoundLibrary = {

	ui = {
		buttonClick = "rbxassetid://73270840594679",
		success     = "rbxassetid://135165335432475",
	},

	gameplay = {
		npcHit      = "rbxassetid://131712160050283",
		checkpoint  = "rbxassetid://92629074359427",
	},

	bgm = {
		lobby       = "rbxassetid://1839151281",
		easy        = "rbxassetid://84690059841117",
		normal      = "rbxassetid://122005885614599",
		hard        = "rbxassetid://71725806523037",
	}
}

return SoundLibrary