--==================================================
-- SoundLibrary.luau
-- サウンドID定義（Shared）
--==================================================

local SoundLibrary = {

	ui = {
		buttonClick = "rbxassetid://12222005",
		success     = "rbxassetid://138081500",
	},

	gameplay = {
		npcHit      = "rbxassetid://911882310",
		checkpoint  = "rbxassetid://138081500",
	},

	bgm = {
		stage1      = "rbxassetid://1234567890",
		stage2      = "rbxassetid://1234567891",
	}
}

return SoundLibrary